name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "Install Tracer Client in your workflow"

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -e

        # Install Tracer Client with or without user ID
        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
        fi

        # Use sudo for installation in GitHub Actions environment
        curl -sSL https://install.tracer.cloud/ | sudo bash

        # Add Tracer to PATH for all subsequent workflow steps
        echo "/root/.tracerbio/bin" | sudo tee -a $GITHUB_PATH

        # Also set PATH for current step
        export PATH="/root/.tracerbio/bin:$PATH"

    - name: "Verify Tracer Client"
      shell: bash
      run: |
        # Verify installation
        if [ -f "/root/.tracerbio/bin/tracer" ]; then
          sudo /root/.tracerbio/bin/tracer info
        else
          echo "Tracer binary not found at expected location"
          exit 1
        fi
