name: "Install Tracer Client"
author: "Vaibhav Upreti"
description: "GitHub Action to install the Tracer CLI client for your workflows."

branding:
  color: "blue"
  icon: "activity"

inputs:
  tracer_user_id:
    description: "Tracer User ID (optional, for personalized setup)"
    required: false
  cli_branch:
    description: "Install Tracer from a custom CLI branch (must be a PR branch)"
    required: false
    default: "main"
  installer_branch:
    description: "Use installer from a custom branch (must be a PR branch)"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: "Install Tracer Client"
      shell: bash
      run: |
        set -euo pipefail

        if [ -n "${{ inputs.tracer_user_id }}" ]; then
          export TRACER_USER_ID="${{ inputs.tracer_user_id }}"
          echo "Using TRACER_USER_ID: $TRACER_USER_ID"
        fi

        CLI_BRANCH_ARG="CLI_BRANCH=\"${{ inputs.cli_branch }}\""
        INS_BRANCH_ARG="INS_BRANCH=\"${{ inputs.installer_branch }}\""
        echo "Using CLI branch: ${{ inputs.cli_branch }}"
        echo "Using installer branch: ${{ inputs.installer_branch }}"

        eval "curl -sSL https://install.tracer.cloud | $CLI_BRANCH_ARG $INS_BRANCH_ARG sh"

        export PATH="$HOME/.tracer/bin:$HOME/.local/bin:$PATH"

        # Verify installation
        if command -v tracer >/dev/null 2>&1; then
          VERSION=$(tracer --version)
          echo "Tracer installed successfully: $VERSION"
        else
          echo "Tracer installation failed or not in PATH"
          exit 1
        fi
